### ISSUE TITLE
test data

### ISSUE THREAD

**Issue by yuyanjie** [MaureenZOU/TSAM#1]
Can you provoid test data example? trainer_sttn.py? inference_sttn.py?

**Comment by MaureenZOU** [comment]
Yeap, I could provide the test data example (Will proceed that once I have time, or I could email you a beta version if you want shortly). For trainer_sttn.py and inference_sttn.py that is for my own practice purpose, I apologize that I could not provide these scripts.

**Comment by yuyanjie** [comment]
Great! I am glad to receive  a beta version. In addition, I can't downloaded model from 'http://www.cmlab.csie.ntu.edu.tw/~zhe2325138/i3d_rgb_imagenet.pt'. Can you send it to me? Thank you very much! My email is 26419543@qq.com

**Comment by MaureenZOU** [comment]
Here is the i3d model: https://drive.google.com/file/d/14eRdVxCeO4Q90YPyTJGDh96dV8XVIlzz/view
I will send you the link with test data. Thanks!
