### ISSUE TITLE
Dear Dr. ZOU. 

### ISSUE THREAD

**Issue by tonitopark** [MaureenZOU/TSAM#12]
I'm trying go over your paper. I was wondering how do you generate the flow related datasets.  Could you please let me know how do you generate the datasets in the following folders: 
            "root_flows_dir": "../../../../data/FVI/Train/flow/",
            "root_flowmasks_dir": "../../../../data/FVI/Train/flow_mask/",

Thanks in advance!

**Comment by MaureenZOU** [comment]
I have updated this on update sections. Thanks a lot!
