### ISSUE TITLE
Which pre-trained model do I need to choose?

### ISSUE THREAD

**Issue by hitachinsk** [MaureenZOU/TSAM#13]
Hello Zou,
Thanks for your excellent work, I noticed you have released the pre-trained models, but there are several checkpoints in the folder, which one do you recommand for the inference on DAVIS dataset?

I'm looking forward to your reply, thank you!

**Comment by MMakarand** [comment]
Hello  Zou,

Thanks for your open-source code.
I am trying to use your code for video inpainting inference on DAVIS dataset and facing the same problem as hitachinsk. Can you guide me on which model to use?
I am running inference on cpu and below is command

test.py
--config config/config_finetune_davis.json --dataset_config dataset_configs/DAVIS_removal.json -p "data\checkpoints\tsm_flowguide_bn8_lr0.00025_wg0.05_finetune_fvi\checkpoint-epoch270.pth"

Note i have tried all checkpoints but i always get following error

{inference.py:471} ERROR - "__getstate__ not in root_dir_names {'masked_frames': '../../../../data/VOS_resized2\\\\masked_frames', 'result_frames': '../../../../data/VOS_resized2\\\\result_frames', 'optical_flows': '../../../../data/VOS_resized2\\\\optical_flows'}"
Could you guide me on this?

**Comment by MaureenZOU** [comment]
To the best of my memory here is the corresponding weight:
	TSAM FVI stationary mask: tsm_flowguide_bn8_lr0.00025_wg0.1_stationary_finetune_fvi/checkpoint-epoch245.pth
	TSAM FVI curve/object mask: tsm_flowguide_bn8_lr0.00025_wg0.05_finetune_fvi/checkpoint-epoch270.pth
	
	TSAM DAVIS stationary mask: tsm_flowguide_bn2_lr0.0001_gan0.1_fvi/checkpoint-epoch165.pth
	TSAM DAVIS curve/object mask: tsm_flowguide_bn2_lr0.0001_gan0.1_noflowmask_fvi/checkpoint-epoch145.pth

**Comment by hitachinsk** [comment]
Thanks for your help! Your work is excellent.

**Comment by DidaDidaDidaD** [comment]
> 你好邹
> 
> 感谢您的开源代码。 我正在尝试使用您的代码在 DAVIS 数据集上进行视频修复推断，并面临与 hitachinsk 相同的问题。你能指导我使用哪种型号吗？ 我在 cpu 上运行推理，下面是命令
> 
> test.py --config config/config_finetune_davis.json --dataset_config dataset_configs/DAVIS_removal.json -p "data\checkpoints\tsm_flowguide_bn8_lr0.00025_wg0.05_finetune_fvi\checkpoint-epoch270.pth"
> 
> 请注意，我已经尝试了所有检查点，但我总是收到以下错误
> 
> {inference.py:471} 错误 - “ **getstate**不在 root_dir_names {'masked_frames': '../../../../data/VOS_resized2\\masked_frames', 'result_frames': '../.. /../../data/VOS_resized2\\result_frames', 'optical_flows': '../../../../data/VOS_resized2\\optical_flows'}" 你能指导我吗？

我也遇到了这个问题
