### ISSUE TITLE
For custom data

### ISSUE THREAD

**Issue by XiaoqiangZhou** [MaureenZOU/TSAM#17]
Thanks for sharing such a great video inpainting work.

While you provide the script and files to train/test the FVI and Davis dataset, it is still difficult to implement this method on personal custom data. Could you please provide more guidance on how to implement your method on a custom data, e.g., test a specified video with a fixed mask.

Thanks.

**Comment by JaeYeonKang** [comment]
Same issues for me.

Is there any full demo code for custom datasets? 
or Could you explain how to get 'flow_removal_complete', 'flownet_removal_complete_mask' ?
Maybe i think you used FGVC's flow completion algorithm for 'flow_removal_complete', but i don't understand how to save flow images likes yours.

Thanks.

**Comment by italosalgado14** [comment]
I have the same problem to use the project with a custom video/data :(

**Comment by MaureenZOU** [comment]
I sincerely apologize that I do not have code for the custom dataset.
