### ISSUE TITLE
大家的能力真强啊，居然都能运行起来，为什么我各种错

### ISSUE THREAD

**Issue by DidaDidaDidaD** [MaureenZOU/TSAM#24]
大家的能力真强啊，居然都能运行起来，为什么我各种错，没想到发cvpr的人，如何运行demo连个小白都不会教，不得不让人吐槽

**Comment by MaureenZOU** [comment]
Could you please share your error message?

**Comment by DidaDidaDidaD** [comment]
> Could you please share your error message?

感谢大佬百忙之中回复，我刚接触这个领域，通过主页您的操作说明，确实各种报错，对小白确实不友好，通过json里的一些数据解析，里面各种配置，源码就两个大文件夹，然后又自建各种目录，建议直接将您能运行的那种目录结构和如何搭配不同的json文件做个简单的说明。我遇到的问题应该就是模型加载的不对、数据加载的不对的问题。给人的感觉整体都很混乱，无从下手的感觉，其他的几个源码demo跑起来确实没难度，但您这个源码运行起来确实要费很大的劲研究出错问题
KeyError: "__getstate__ not in root_dir_names {'masked_frames': '../../../../data/VOS_resized2\\\\masked_frames', 'result_frames': '../../../../data/VOS_resized2\\\\result_frames', 'optical_flows': '../../../../data/VOS_resized2\\\\optical_flows'}"
--Call--
> e:\software-install-dir\anaconda3\envs\videoenv\lib\multiprocessing\util.py(205)__call__()
-> def __call__(self, wr=None,

**Comment by MaureenZOU** [comment]
It seems that you don't provide the full error message. And it seems that the problem is on you do not set the folder correctly. In addition, "e:\" seems to represent that you are using a windows system. All the training and evaluation pipeline is tested on linux system.

**Comment by DidaDidaDidaD** [comment]
> It seems that you don't provide the full error message. And it seems that the problem is on you do not set the folder correctly. In addition, "e:" seems to represent that you are using a windows system. All the training and evaluation pipeline is tested on linux system.

是的，主页上没说用linux，我就在windows下运行的。建议您把运行方法写的详细一些，这样小白按照指示也能快速的运行起来，建议您参照[E2FGVI](https://github.com/MCG-NKU/E2FGVI)，2022年的cvpr，运行起来很简单。
