### ISSUE TITLE
No file named "futils" and "futils.writeSeqHTML" raises undefined name error

### ISSUE THREAD

**Issue by feiyangsuo** [MaureenZOU/TSAM#5]
In file "src/xy_scripts/utils/visualizer.py" line 23 - 27:
```
    def write(self, _sorted=True):
        if _sorted == True:
            futils.writeSeqHTML(self.html_file, sorted(self.dir_lst), sorted(self.caption_lst), self.col, self.size[0], self.size[1])
        else:
            futils.writeSeqHTML(self.html_file, self.dir_lst, self.caption_lst, self.col, self.size[0], self.size[1])
```
while name `futils` is not declared before. I assume it should be imported in file "src/xy_scripts/utils/__init__.py" but this line `from . import futils` is committed out. And there's no such file. 

Maybe writeSeqHTML is moved into other methods of another file?

**Comment by MaureenZOU** [comment]
Hi feiyang, thanks for your question. I have removed futils when uploading codes as that file is not written by me. I believe this will not influence training and evaluation. Please feel free to reply if that file influence training and evaluation, Thanks!
