### ISSUE TITLE
final weights for demo

### ISSUE THREAD

**Issue by JaeYeonKang** [MaureenZOU/TSAM#7]
Hi. Thanks for nice work.
The question is..
Is there final weights for demo instead of pre-trained resent weights for training?
I want to run demo for my own testsets.

**Comment by MaureenZOU** [comment]
Please send me emails for trained weights. Thanks a lot!

**Comment by sydney0zq** [comment]
> Hi. Thanks for nice work.
> The question is..
> Is there final weights for demo instead of pre-trained resent weights for training?
> I want to run demo for my own testsets.

Hi, could you please send me a copy of the pretrain weights? Thanks. My Email is theodoruszq@gmail.com.

**Comment by UrskaJ** [comment]
I would be also happy to get the pretrained weights - can you share your email or a link where they are available?
